name: build-test
on:  
  push: 
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v2
        with:
          tags: gateway-sidecar:latest
          push: false
